; ui_url = https://aviasales.ru/search
; ui_auth_url = https://aviasales.ru

; name="identifier"
https://api.travelpayouts.com/aviasales/v3/prices_for_dates?origin=MOW&destination=DXB&departure_at=2023-07&return_at=2023-08&unique=false&sorting=price&direct=false&currency=rub&limit=10&page=1&one_way=true&token=Ваш_ключ_API"
https://api.travelpayouts.com/aviasales/v3/prices_for_dates?origin=MOW&destination=DXB&departure_at=2023-07&return_at=2023-08&unique=false&sorting=price&direct=false&currency=rub&limit=10&page=1&one_way=false&token=РазместитеЗдесьВашКлюч"